version: '3.7'

services:
  db:
    image: postgres
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: webapp:0.2.0
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
