version: '3.7'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=qwerty1234 
    ports:
      - "5432:5432"

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: webapp:0.2.0
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:qwerty1234@db/postgres
    depends_on:
      - db
