# Generated by Django 2.2.5 on 2019-10-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answermodel',
            old_name='answer',
            new_name='question',
        ),
    ]
