# Generated by Django 2.2.5 on 2019-10-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendsmodel',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
