# Generated by Django 2.2.5 on 2019-10-16 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20191016_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answermodel',
            name='question',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ask.AnswerModel'),
        ),
    ]
