# Generated by Django 2.2.5 on 2019-11-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_friendsmodel_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
